name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r .github/workflows/requirements.txt

      - name: Run Tests
        run: python manage.py test

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r . $USER@$HOST:/home/ubuntu/djangodemo_UI
          ssh -i private_key.pem $USER@$HOST "cd /home/ubuntu/djangodemo_UI && source venv/bin/activate && python manage.py migrate && /home/ubuntu/.local/bin/gunicorn djangodemo_UI.wsgi:application --bind 0.0.0.0:8000"

